### ISSUE TITLE
文档定位有个bug应该。

### ISSUE THREAD

**Issue by y1324** [NICEXAI/leaflet_zh#14]
我在qq群里发视频，麻烦看下处理下吧。

在左边栅格图层菜单里点，里面的子菜单定位不了具体的位置。只是往上挪一挪。

谷歌浏览器

**Comment by NICEXAI** [comment]
非常感谢，问题已收到。
我晚上将会排查并处理该问题。

**Comment by NICEXAI** [comment]
问题已确认，这是一个来自leafletjs官方的一个BUG。稍后我们

**Comment by NICEXAI** [comment]
问题已修复

**Comment by y1324** [comment]
> 问题已修复

感谢
